### ISSUE TITLE
Problems running the command  gsettings set org.gnome.shell.extensions.user-theme name "omni"

### ISSUE THREAD

**Issue by felipsbreno** [getomni/gtk-omni#4]
#  What I did to activate the theme

I downloaded the zip available in the repository, extract it to a folder in the suggested path `/ usr / share / themes`.

However when I run the second command passed to activate the theme it does not activate.

command run  `gsettings set org.gnome.shell.extensions.user-theme name "omni"`

response returned  `Nenhum esquema “org.gnome.shell.extensions.user-theme”`

Any commands to be able to create the scheme to activate tem?

**Comment by jpedroschmitz** [comment]
Hey @breno-felipe, thanks for reporting this.

@JeffSilva01, could you take a look at this issue?

If anyone knows how to solve it, please share it here! 
I can't test it out because I'm on macOS right now.

**Comment by birobirobiro** [comment]
> # What I did to activate the theme
> I downloaded the zip available in the repository, extract it to a folder in the suggested path `/ usr / share / themes`.
> 
> However when I run the second command passed to activate the theme it does not activate.
> 
> command run `gsettings set org.gnome.shell.extensions.user-theme name "omni"`
> 
> response returned `Nenhum esquema “org.gnome.shell.extensions.user-theme”`
> 
> Any commands to be able to create the scheme to activate tem?

You can use Gnome tweaks to activate the theme

To do this, just follow these steps:

- Clone the repository
- Move the **gtk-main** folder to `/usr/share/themes`
- Install Gnome Tweaks via the store
- Open Gnome Tweaks and go to Appearance
- Select Gtk-main and the theme will be applied

If you want the shell to look like this, you need to install the User Themes extension

https://extensions.gnome.org/extension/19/user-themes/

![image](https://user-images.githubusercontent.com/22185823/111214408-abeb6080-85b0-11eb-81b6-7f7dc8671807.png)

**Comment by jpedroschmitz** [comment]
Thanks, @birobirobiro!

I'll be closing this for now! In case anyone runs into it again, let me know.
